export const CAMPAIGN_LOADED_SUCCESS = 'CAMPAIGN_LOADED_SUCCESS';
export const CAMPAIGNS_LOADED_SUCESS = 'CAMPAIGNS_LOADED_SUCESS';
export const LOAD_PURE_PROFILE_INSTANCES_SUCCESS = 'LOAD_PURE_PROFILE_INSTANCES_SUCCESS';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_CSS_STYLES_SUCCESS = 'LOAD_CSS_STYLES_SUCCESS';

export const REDIRECT = 'REDIRECT';
export const APP_LOAD = 'APP_LOAD';
export const LOGOUT = 'LOGOUT';

export const ASYNC_START = 'ASYNC_START';
